name: Mono

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Packages
      run: |
        sudo apt-get install -y apt-transport-https dirmngr
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu vs-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
        sudo apt-get update
        sudo apt-get install -y mono-complete monodevelop nuget
    - name: Configure
      run: ./configure --git-submodule
    - name: Build
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-target
        path: build/target/*
    - name: Push Markdown Documentation
      uses: EndBug/add-and-commit@v7
      with:
        add: 'src/KeybindLib/README.md'
        default_author: github_actions
        message: 'Auto-update markdown documentation.'
